{% set name = "museval" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff12e3bd60fb7ef3dd4c87ecad829e4d9c47dfc698ae74bac5eba7511a35e73d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: noarch

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas >=0.25.0
    - numpy
    - scipy
    - simplejson
    - pysoundfile
    - jsonschema
    - musdb

test:
  imports:
    - museval

about:
  home: https://github.com/sigsep/sigsep-mus-eval
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: museval - source separation evaluation tools for python
  doc_url: https://sigsep.github.io/sigsep-mus-eval
  dev_url: https://github.com/sigsep/sigsep-mus-eval

extra:
  recipe-maintainers:
    - Faylixe
